### PR TITLE
Support extensions (documentation)

### PR DESCRIPTION
**Pull request by moelders**
Hello, I have been facing the showdown extensions using this plugin, and I think it is a good idea to update the documentation of this plugin. You can see my changes.

Changelog:
- Update `options` object documentation with `extensions`.
- Update `showdown` to 1.9.0.
- Add extensions documentation in the guide section.
- Add `package-lock.json`.

Pending tasks:
- Translate the new extensions section in the `docs/zh/guide/index.md`.
- Build distribution files and documentation.

### CODE REVIEW

**Comment by meteorlxy** [comment]
@moelders Thanks for your PR! I'll check in detail later.

BTW, is it a good idea to have both `package-lock.json` and `yarn.lock` in a same repo?

**Comment by moelders** [comment]
As I do not use yarn I am not sure about the answer. If you prefer to rely on yarn I can remove the `package-lock` and add it to the `.gitignore`.

**Comment by moelders** [comment]
I have just reading this [Yarn post](https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/) about compatibility with `package-lock` from version `1.7.0`.

But no problem, I can remove it and you can update `yarn.lock`.

**Comment by meteorlxy** [comment]
I didn't include extensions in the docs because ~~I was lazy~~ I thought `extensions` is also one of the property of `options`. But yeah it would be better to mention it in our docs, too.

I'll merge this PR after some tweaks and transilations. 😄

**Comment by meteorlxy** [comment]
@moelders 

I've bumped `vue-showdown` to v2.2.0 with some breaking changes, which makes the usage of extensions different.

It will be nice if you have time to check them and give some suggestions. Thanks in advance 😄

**Pull request merged**
